// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/ratelimiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	WindowSecs    int32                  `protobuf:"varint,4,opt,name=window_secs,json=windowSecs,proto3" json:"window_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *CheckRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckRequest) GetWindowSecs() int32 {
	if x != nil {
		return x.WindowSecs
	}
	return 0
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RuleId        string                 `protobuf:"bytes,5,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *CheckResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CheckResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *CheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_ratelimiter_proto protoreflect.FileDescriptor

const file_api_proto_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/ratelimiter.proto\x12\vratelimiter\"\x80\x01\n" +
	"\fCheckRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vwindow_secs\x18\x04 \x01(\x05R\n" +
	"windowSecs\"\xb1\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x17\n" +
	"\arule_id\x18\x05 \x01(\tR\x06ruleId\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error2M\n" +
	"\vRateLimiter\x12>\n" +
	"\x05Check\x12\x19.ratelimiter.CheckRequest\x1a\x1a.ratelimiter.CheckResponseB5Z3github.com/Zartex-the-art/sei-ratelimiter/api/protob\x06proto3"

var (
	file_api_proto_ratelimiter_proto_rawDescOnce sync.Once
	file_api_proto_ratelimiter_proto_rawDescData []byte
)

func file_api_proto_ratelimiter_proto_rawDescGZIP() []byte {
	file_api_proto_ratelimiter_proto_rawDescOnce.Do(func() {
		file_api_proto_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ratelimiter_proto_rawDesc), len(file_api_proto_ratelimiter_proto_rawDesc)))
	})
	return file_api_proto_ratelimiter_proto_rawDescData
}

var file_api_proto_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_ratelimiter_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: ratelimiter.CheckRequest
	(*CheckResponse)(nil), // 1: ratelimiter.CheckResponse
}
var file_api_proto_ratelimiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.RateLimiter.Check:input_type -> ratelimiter.CheckRequest
	1, // 1: ratelimiter.RateLimiter.Check:output_type -> ratelimiter.CheckResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ratelimiter_proto_init() }
func file_api_proto_ratelimiter_proto_init() {
	if File_api_proto_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ratelimiter_proto_rawDesc), len(file_api_proto_ratelimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ratelimiter_proto_goTypes,
		DependencyIndexes: file_api_proto_ratelimiter_proto_depIdxs,
		MessageInfos:      file_api_proto_ratelimiter_proto_msgTypes,
	}.Build()
	File_api_proto_ratelimiter_proto = out.File
	file_api_proto_ratelimiter_proto_goTypes = nil
	file_api_proto_ratelimiter_proto_depIdxs = nil
}
